### ISSUE TITLE
Upgrade bip_utils to version 2.1.0 due to backward incompatibility

### ISSUE THREAD

**Issue by behnamhatami** [vechain/thor-devkit.py#11]

**Comment by laalaguer** [comment]
A breaking change in the underlying library. Thanks for bringing it upfront. I will take a look at it.

**Comment by laalaguer** [comment]
Rerwote the underlying library have done the job of incompatibility. Won't introduce bip_utils > 2.0 becuase it now depends on exessive libraries. Issue closed.
