### ISSUE TITLE
I change some lib version  in  thor-devkit . and get this error    ImportError: cannot import name 'Bip32' from 'bip_utils'

### ISSUE THREAD

**Issue by SheydaAshoorian** [vechain/thor-devkit.py#14]
I change some lib version  in  thor-devkit . and get this error    ImportError: cannot import name 'Bip32' from 'bip_utils'

pysha3==1.0.2
pytest~=6.2.2
pytest-cov
ecdsa>=0.17.0
eth-keys<0.4.0,>=0.3.4
mnemonic==0.19
bip-utils==2.4.0
eth-keyfile==0.5.1
rlp==1.2.0
eth-abi==2.1.1
voluptuous==0.12.0
wheel
twine

**Comment by laalaguer** [comment]
`bip_utils 2.4.0` doesnt have `Bip32`.
